version: "3.8"

services:


  configserver:
    image: montasermahadi/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - montasermahadi
      
  eurekaserver:
    image: montasermahadi/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
     - montasermahadi
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  account:
    image: montasermahadi/account:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - montasermahadi
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
  
  loans:
    image: montasermahadi/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - montasermahadi
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    
  cards:
    image: montasermahadi/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - montasermahadi
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

networks:
  montasermahadi: